import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import LeftSiderBar from "@/components/layout/LeftSideBar/page";
import Top from "@/components/layout/Top/page";
import RightSiderBar from "@/components/layout/RightSiderBar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={`${inter.className} bg-slate-800 text-white ` }>
        <main className="flex flex-row  justify-between m-auto gap-10 ">
          <div className=" flex " >
          <LeftSiderBar></LeftSiderBar>
          </div>
          <div className="items-center w-[60%] flex-1 h-[1200px] ">
            <Top></Top> 
            {children}
          </div>
          <div className=" flex ">
          <RightSiderBar></RightSiderBar>
          </div>
        </main>
        </body>
    </html>
    </ClerkProvider>
  );
}
